### ISSUE TITLE
Voltaxic Rift makes you invincible

### ISSUE THREAD

**Issue by Bedirhanium** [Some-Bunny/Modular#2]
Having a few blackholes in a room (maybe even one is enough) and lots of bullets (by lots, i mean around 15-20, not that much), all bullets start phasing through you and you can only take "touching" damage, if you touch a monster directly. 

Idk if it overloads some kind of "maximum hit/second" for overall game or maybe some other stuff, maybe its due to the distortion of blackholes and stuff that breaks the entire game, but all i know is that it is not a visional bug, i can EASILY replicate this bug with any kind of module combination, maybe even without any modules, and be invincible in almost every bossfight. I know phasing through every bullet in the dragon fight in the 2nd phase, thanks to this bug alone

![image](https://github.com/Some-Bunny/Modular/assets/146653837/dc540e35-04f2-4ec5-95e1-a1ff1778527b)

here is a funny picture showing it

**Comment by Some-Bunny** [comment]
i think i know whats going wrong here, will patch hopefully soon

**Comment by Some-Bunny** [comment]
fixed
